# illusion - docker-composer.yml of mariadb + redis + phpmyadmin, for sample only.
# (c) 2025 Shiranui (https://shiranui.xyz)

version: "3.5"
services:
  database:
    image: mariadb:10.10
    container_name: illusion-data
    ports:
      - 127.0.0.1:2001:3306
    volumes:
      - database:/var/lib/mysql:rw
      - ./.illusion-dump:/usr/local/bin/dumpfiles:ro
      - ./dump:/dump:rw
    networks:
      - illusion
    env_file:
      - .env.default
      - .env.local
    restart: always

  cache:
    image: redis:7.0
    container_name: illusion-cache
    ports:
      - 127.0.0.1:2002:6379
    networks:
      - illusion
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2
    container_name: illusion-pma
    ports:
      - 127.0.0.1:2003:80
    networks:
      - illusion
    environment:
      PMA_HOST: "illusion-data"
    restart: always

volumes:
  database:
    driver: local

networks:
  illusion:
    name: illusion
    driver: bridge
